name: 'Telegram Notification Action'
description: 'Telegram send message action'
author: 'an3park'
inputs:
  job_status:
    description: 'Job status, default: job.status'
    default: ${{ job.status }}
  # https://core.telegram.org/bots/api#sendmessage
  bot_token:
    description: 'Bot token'
    required: true
  chat_id:
    description: 'Unique identifier for the target chat or username of the target channel (in the format @channelusername)'
    required: true
  message_thread_id:
    description: 'Unique identifier for the target message thread (topic) of the forum; for forum supergroups only'
  message:
    description: 'Text of the message to be sent, 1-4096 characters after entities parsing'
    required: true
  parse_mode:
    description: 'MarkdownV2 | HTML | Mode for parsing entities in the message text. See [formatting options](https://core.telegram.org/bots/api#formatting-options)'
    default: 'MarkdownV2'
  disable_web_page_preview:
    description: 'Disables link previews for links in the message'
    default: 'false'
  disable_notification:
    description: 'Sends the message silently. Users will receive a notification with no sound.'
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'message-square'
  color: 'blue'
