name: 'Telegram Notification Action'
description: 'Telegram Notification Action'
author: 'an3park'
inputs:
  bot_token:
    required: true
    description: 'Bot token'
  chat_id:
    required: true
    description: 'Unique identifier for the target chat or username of the target channel (in the format @channelusername)'
  message_thread_id:
    required: false
    description: 'Unique identifier for the target message thread (topic) of the forum; for forum supergroups only'
  message:
    required: true
    description: 'Text of the message to be sent, 1-4096 characters after entities parsing'
  parse_mode:
    default: 'MarkdownV2'
    required: false
    description: 'Mode for parsing entities in the message text. See [formatting options](https://core.telegram.org/bots/api#formatting-options)'

runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'message-square'
  color: 'blue'
